# Generated by Django 3.2.2 on 2022-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_availablebookinsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='issue_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Borrowed'), (2, 'Available')], default=2, null=True),
        ),
    ]
